[settings]
locked = true
lockfile = true
experimental = true
paranoid = false
github.slsa = false
github.github_attestations = false
aqua.github_attestations = false
aqua.cosign = false
aqua.slsa = false
aqua.minisign = false

[tools]
"github:nushell/nushell" = "0.104.0"
"aqua:ollama/ollama" = "0.18.2"
node = "22.14.0"
"github:pnpm/pnpm" = "9.15.2"
